#!/home/akiyama8192/anaconda3/bin/python3
#SPDX-FileCopyrightText: 2025 Taiki Akiyama
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
